esphome:
  name: node2
  friendly_name: NODE2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "W08UNo3XkmSY/sSE9BcU7zevEWxXO3zySFfYFD26BGI="

ota:
  password: "cbfa28ebac630cdeb991ac07d8f05b9b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Node2 Fallback Hotspot"
    password: "4FKN69EWy2eh"

captive_portal:


i2c:
  sda: GPIO2
  scl: GPIO0
  scan: true

sensor:
  - platform: bmp280
    temperature:
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      name: "Outside Pressure"
    address: 0x76
    update_interval: 60s
    
    