esphome:
  name: polyhouse1temperaturesensor1
  friendly_name: Polyhouse1.TemperatureSensor1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BquWdDclRq2dOxVuIAg+AQ5uyaiU+/hOGV4LtatN570="

ota:
  password: "01f35b3e1f6b5722bda12cb07420431f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Polyhouse1Temperaturesensor1"
    password: "pXlkomGFkRIg"

captive_portal:

i2c:
  sda: GPIO2
  scl: GPIO0
  scan: true

sensor:
  - platform: bmp280
    temperature:
      name: "temperature"
      oversampling: 16x
    pressure:
      name: "pressure"
    address: 0x76
    update_interval: 60s
  - platform: bh1750
    name: "illuminance"
    address: 0x23
    update_interval: 60s
    