esphome:
  name: polyhouse1controller
  friendly_name: Polyhouse1.Controller

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Kh6OLIsTWpu9Y0v6Z+/aEiUdH/168GP0Qoj0xQRByhU="

ota:
  password: "ca93b971147093a357e21942808e3577"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Polyhouse1Controller"
    password: "7d51WxS3Yb1H"

i2c:
  sda: 16
  scl: 17

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 60s

switch:
  - platform: gpio
    pin: 14
    name: "Relay 1"
    inverted: True
    id: relay1
  - platform: gpio
    pin: 15
    name: "Relay 2"
    inverted: True
    id: relay2
    