esphome:
  name: zerow
  friendly_name: ZeroW

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dsh+U921/GiJha+kwYBlzxRNgvkeNZ4sNbZuytJM01E="

ota:
  password: "a4698569c2ef912b3610569b798ba0ba"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Zerow Fallback Hotspot"
    password: "kto8VYAoy0ow"

  # manual_ip:
  #  static_ip: 192.168.137.227
  #  gateway: 192.168.137.1
  #  subnet: 255.255.255.0

i2c:
  sda: 16
  scl: 17

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 60s
  - platform: bh1750
    name: "illuminance"
    address: 0x23
    update_interval: 60s

switch:
  - platform: gpio
    pin: 14
    name: "Relay 1"
    inverted: True
    id: relay1
  - platform: gpio
    pin: 15
    name: "Relay 2"
    inverted: True
    id: relay2