
# Loads default set of integrations. Do not remove.
default_config:

system_health:

mobile_app:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

api:

panel_iframe:
  vscode:
    title: "VSCode"
    url: "http://localhost:8443/"
    icon: mdi:microsoft-visual-studio-code
    require_admin: true
  esphome:
    title: "ESPHome"
    url: "http://localhost:6052"
    require_admin: true
    icon: mdi:chip
  zigbee2mqtt:
    title: "Zigbee2MQTT"
    url: "http://localhost:8080"
    icon: mdi:zigbee
    require_admin: true

################################## SENSORS #####################################

# TIME/DATE SENSOR
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

# TEMPLATE VPD SENSORS
sensor:
  - platform: template
    sensors:
      vapor_deficit:
        friendly_name: "Vapor Pressure Deficit(kPa)"
        value_template: >-
          {% set T = (states('sensor.zerow_temperature') | float) %}
          {% set RH = states('sensor.zerow_humidity')|float %}
          {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %}
          {% set VPD = ((100-RH) / 100) * SVP %}
          {{-VPD | round(2) -}}
        unit_of_measurement: 'kPa'

################################ INPUTS #################################

input_number:
  tds_input:
    name: TDS Input
    min: 100
    max: 500
  ph_input:
    name: PH Value
    min: 1
    max: 14
    step: .1
    icon: mdi:bullseye
    unit_of_measurement: pH