version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - ~/wasser/docker-volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"

  #VSCode
  vscode:
    container_name: vscode
    image: codercom/code-server
    volumes:
      # Set <project dir> to the directory you want to open in VS Code.
      - ~/wasser/docker-volumes:/config
      # <vs code config> should point to a local dir where vs code stores its data.
      - ~/wasser/docker-volumes/vscode:/home/coder/.local/share/code-server
    ports:
      - "8443:8080"
    command: code-server --auth none --disable-telemetry /config
    restart: unless-stopped

  #Mosquitto
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      # This port is for Webhooks
      # - "9001:9001"
    volumes:
      - ~/wasser/docker-volumes/mosquitto/config:/mosquitto/config
      - ~/wasser/docker-volumes/mosquitto/data:/mosquitto/data
      - ~/wasser/docker-volumes/mosquitto/log:/mosquitto/log

  #ESPHome
  esphome:
    container_name: esphome
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      # Update PATH_TO_YOUR_CONFIG, the :rw gives the container Read/Write access
      - ~/wasser/docker-volumes/esphome:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # You do have to map a serial port here. Determine your port and uncomment.
    #devices:
    #  - /dev/ttyAMC0:/dev/ttyAMC0
    restart: unless-stopped

  #Node-Red
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ~/wasser/docker-volumes/nodered:/data
    restart: unless-stopped
    depends_on:
      - homeassistant
      - mosquitto

  #Zigbee2MQTT
  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   depends_on:
  #     - mosquitto
  #   image: koenkk/zigbee2mqtt
  #   volumes:
  #     - /PATH_TO_YOUR_DATA:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     # Frontend port
  #     - 8080:8080
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 100M
  #   restart: always
  #   privileged: true

  #Rhasspy
  # rhasspy:
  #   image: "rhasspy/rhasspy"
  #   container_name: rhasspy
  #   restart: unless-stopped
  #   volumes:
  #       - "$HOME/.config/rhasspy/profiles:/profiles"
  #       - "/etc/localtime:/etc/localtime:ro"
  #   ports:
  #       - "12101:12101"
  #   devices:
  #       - "/dev/snd:/dev/snd"
  #   command: --user-profiles /profiles --profile en
